apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest
              args:
                - curl
                - "{{ .Values.cronjob.url }}"
          restartPolicy: OnFailure
